### ISSUE TITLE
Cell::Rails can't be used without a parent controller

### ISSUE THREAD

**Issue by rainhead** [trailblazer/cells#112]
Somewhere between 3.5 and 3.8.2, we can no longer have a cell which inherits from Cell::Rails and sometimes has a parent controller, and sometimes doesn't. I.e., is sometimes called when servicing a request, and sometimes when not.

Perhaps the parent_controller stuff should be moved into Cell::Base and made optional?

**Comment by kreintjes** [comment]
Same problem over here. I have cells-rails included in my project and I have a Cell which sometimes is rendered from a view/controller, and sometimes from a model (in a background job). In this cell I am using the high_chart helper from the [lazy_high_charts](https://github.com/michelson/lazy_high_charts) gem. This gem does a check somewhere if there is an xhr request going on, and uses the request object for that: https://github.com/michelson/lazy_high_charts/blob/f7d4d1614816c98d81d9d7d387d4b6e0a9901d05/lib/lazy_high_charts/layout_helper.rb#L76

Now rendering the cell from the model fails, because request delegates to parent_controller, which isn't available at that point. Full error and backtrace:

```
NoMethodError: undefined method `[]' for nil:NilClass
/gems/2.4.0/gems/cells-rails-0.0.8/lib/cell/rails.rb:58:in `parent_controller'
/2.4.0/forwardable.rb:223:in `request'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:77:in `request_is_xhr?'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:95:in `encapsulate_js'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:40:in `build_html_output'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:24:in `high_graph'
/gems/2.4.0/bundler/gems/lazy_high_charts-c21849e7e1f4/lib/lazy_high_charts/layout_helper.rb:10:in `high_chart'
app/cells/analysis/chart.slim:2:in `block in singleton class'
app/cells/analysis/chart.slim:-2:in `instance_eval'
app/cells/analysis/chart.slim:-2:in `singleton class'
app/cells/analysis/chart.slim:-5:in `__tilt_70304215070660'
/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `call'
/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:170:in `evaluate'
/gems/2.4.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/view_model.rb:118:in `render_template'
/gems/2.4.0/gems/cells-slim-0.0.5/lib/cell/slim.rb:8:in `render_template'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/view_model.rb:110:in `render_to_string'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/layout.rb:23:in `render_to_string'
/gems/2.4.0/gems/cells-4.1.7/lib/cell/view_model.rb:104:in `render'
app/cells/analysis_cell.rb:189:in `chart'
```

The error happens, because context isn't set, thus it can't determine the parent_controller. I could give a context when calling the cell, i.e. `context: { controller: :some_controller }`, but that doesn't fix the error. Now I get a `NoMethodError: undefined method `request' for :some_controller:Symbol`.

I think the problem is that cells-rails defines request, tricking lazy_high_charts into thinking there is an actual request going on, while there isn't. I can perfectly use lazy_high_charts from within a model/job or even just in a Rails console (no controller/request there), but not when I use it within a cell.
