### ISSUE TITLE
Template missing: view: `show.haml` prefixes: ["comment"] view_paths:["app/cells"]

### ISSUE THREAD

**Issue by vwall** [trailblazer/cells#223]
User master and getting Template missing: view: `show.haml` prefixes: ["comment"] view_paths:["app/cells"].

Using SLIM instead of HAML but also can't get it to work with erb.

**Comment by nacengineer** [comment]
FYI I tried to use this code in Rails but to no avail. I also tried 

```rb
render format :erb
```
It would seem that if using two template engines within rails, the first one required by bundlerwins. 

To get it working with both haml and erb, I had to require: false in Gemfile and then include them in the more traditional "ruby only" way to get them to both work.

I'm not sure if this is a bug or I didn't configure properly.  I tried the above inside the class and outside, neither worked. Perhaps a class method for Cell::ViewModel that would override initialized setting would be useful, similar to Rails' table_name settings on models.

**Comment by apotonick** [comment]
That sounds like two unrelated issues, @nacengineer. This ticket was about "activating" the template engine for a cell before 4.0 was released.

You want to use two engines in one project. The problem here is that each gem (cells-haml, etc.) will try to include itself into `Cell::ViewModel`, so the last one wins.

We can't simply provide multiple engines with an option in `#render`, as every template engine needs different helpers to be patched (again, this is not my fault) which implies the cell to include those helpers.

The only real solution is to suppress Cells-in-Rails-mode to automatically include those engines and let the user do it, but then people will complain that this is "not convenient". See the problem? What do you think?

**Comment by nacengineer** [comment]
Yeah  I agree with you  I posted it here because this seemed to be a class method that would allow you to se this on a per cell basis. Just as an FYI that this won't work in rails.  My bad.  I think the current method is fine.  I'll try to add a PR to the docs for using multiple engines in rails.  Sorry for any confusion ☺

**Comment by sveredyuk** [comment]
I have some issue when trying to spec views by capybara in engines.

` Cell::ViewModel.view_paths = %w[engines/core/app/cells]`

`ActionView::Template::Error: Template missing: view: `show.slim` prefixes ["engines/core/app/cells/my_namespace/flash", "engines/core/app/cells/my_namespace/application"]
`

In development ENV everything is OK, but rspec don't run.

I render the cell with = cell 'my_namespace/flash'

How i can solve this ?

**Comment by apotonick** [comment]
@sveredyuk Which Cells version?

**Comment by sveredyuk** [comment]
@apotonick 

```
  s.add_dependency 'cells',                    '~> 4.0.5'
  s.add_dependency 'cells-slim',             '~> 0.0.5'
```

**Comment by apotonick** [comment]
It looks as if your added view path `engines/core/app/cells` is not applied to your cell? Can you see that it's not printed in the exception?

**Comment by sveredyuk** [comment]
Yes, i added, without it, it wouldn't work in any env.

When remove it:
`Template missing: view: `show.slim` prefixes: ["app/cells/my_namespace/flash", "app/cells/my_namespace/application"]`

But i think this issue is only rspec related. Because every time when i am trying spec with view rendering or capybara i got exception 
`ActionView::Template::Error: Template missing: view:show.slim prefixes ["engines/core/app/cells/my_namespace/flash", "engines/core/app/cells/my_namespace/application"] `

**Comment by apotonick** [comment]
Can you come join us on the Gitter channel, please? https://gitter.im/trailblazer/chat
